### ISSUE TITLE
Framework To Add Support / Make Use of............

### ISSUE THREAD

**Issue by varunsridharan** [wponion/dev#1]
### Selected CSS Libs
- [ ] [PrettyCheckbox](https://lokesh-coder.github.io/pretty-checkbox/)

### CSS Library's
- [ ] [FontAwesome](http://fontawesome.com/)
- [ ] [Animate.CSS](https://daneden.github.io/animate.css/)
- [ ] [MagicInput](http://wangchujiang.com/magic-input/) | [PrettyCheckbox](https://lokesh-coder.github.io/pretty-checkbox/)
- [ ] [Effeckt.css](http://h5bp.github.io/Effeckt.css/)

### JS Library's
- [ ] [Select2](http://select2.org)
- [ ] [Selectize](https://selectize.github.io/selectize.js)
- [ ] [Bootstrap Datepicker](https://bootstrap-datepicker.readthedocs.io/en/latest/) 
- [ ] [Bootstrap Timepicker](https://github.com/jdewit/bootstrap-timepicker)
- [ ] [Bootstrap Colorpicker](https://itsjavi.com/bootstrap-colorpicker/) 
- [ ] [Bootstrap Switch](https://github.com/Bttstrp/bootstrap-switch)
- [ ] **Boostrap Maxlength**
- [ ] [ion RangeSlider](https://github.com/IonDen/ion.rangeSlider)
- [ ] [jQuery Validation](https://jqueryvalidation.org/)
- [ ] **jQuery Inputmask**
- [ ] [jQuery MarkdownEditor](https://simplemde.com/)

#### Selectize Addons
- [ ] **click_to_edit** | [Selectize Pull #946](https://github.com/selectize/selectize.js/pull/946) | [Source Code](https://github.com/krissalvador27/selectize.js/blob/5fe5862cb0d918c3f500c53c04f979e8d401a1db/src/plugins/click_to_edit/plugin.js) 
- [ ] **condensed_dropdown**  | [Selectize Pull #944](https://github.com/selectize/selectize.js/pull/944) | [Source Code](https://github.com/rantav/selectize.js/tree/0e45bf604acfd507d150561e39fe83b758cac24b/src/plugins/condensed_dropdown) 
- [ ] **dark_theme**  | [Selectize Pull #447](https://github.com/selectize/selectize.js/pull/447) | [Source Code](https://github.com/mistic100/selectize.js/tree/3bdf50a5e5850905aaf203eab679dc8fe9fae2d7/dist/css) 
- [ ] **bootstrap4_theme** | [Selectize Issue #905](https://github.com/selectize/selectize.js/issues/905) | [Source Code](https://github.com/papakay/selectize-bootstrap-4-style)

### Extra Color Picker Options
- [ ] [jColor - a jQuery Color Picker ](https://codecanyon.net/item/jcolor-a-jquery-color-picker/10688026)
- [ ] [ColoringPick](https://codecanyon.net/item/coloringpick-jquery-gradient-color-picker/21130553?s_rank=3)
- [ ] [MeterialPallet](https://codecanyon.net/item/material-color-picker-plus/20316509?s_rank=5)

**Comment by varunsridharan** [comment]
Settings Page Theme. https://geekman.site/emphasize/ui/panels.html

**Comment by vjchandrika** [comment]
You can add this time picker 
[https://tempusdominus.github.io/bootstrap-4/Usage/](url)

**Comment by varunsridharan** [comment]
https://lcweb.it/lc-switch-jquery-plugin
